---
# CPU Checks
- name: Check CPU
  command: sensuctl check create check-cpu \
          --command 'check-cpu.rb -w 75 -c 90' \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-cpu-checks,sensu-ruby-runtime \
          --handlers slack
  run_once: true
  ignore_errors: true

- name: Check metrics-cpu-mpstat
  command: sensuctl check create metrics-cpu-mpstat \
          --command metrics-cpu-mpstat.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-cpu-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-cpu-pcnt-usage
  command: sensuctl check create metrics-cpu-pcnt-usage \
          --command metrics-cpu-pcnt-usage.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-cpu-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-numastat
  command: sensuctl check create metrics-numastat \
          --command metrics-numastat.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-cpu-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-user-pct-usage
  command: sensuctl check create metrics-user-pct-usage \
          --command metrics-user-pct-usage.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-cpu-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

# Memory Checks
- name: Check check-memory
  command: sensuctl check create check-memory \
          --command check-memory.rb -w 2500 -c 3000 \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-memory-checks,sensu-ruby-runtime \
          --handlers slack
  run_once: true
  ignore_errors: true

- name: Check check-memory-percent
  command: sensuctl check create check-memory-percent \
          --command check-memory-percent.rb -w 70 -c 80 \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-memory-checks,sensu-ruby-runtime \
          --handlers slack
  run_once: true
  ignore_errors: true

- name: Check check-swap-percent
  command: sensuctl check create check-swap-percent \
          --command check-swap-percent.rb -w 70 -c 80 \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-memory-checks,sensu-ruby-runtime \
          --handlers slack
  run_once: true
  ignore_errors: true

- name: Check check-swap
  command: sensuctl check create check-swap \
          --command check-swap.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-memory-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true
  when: ansible_swaptotal_mb > 0

- name: Check metrics-memory-percent
  command: sensuctl check create metrics-memory-percent \
          --command metrics-memory-percent.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-memory-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-memory
  command: sensuctl check create metrics-memory \
          --command metrics-memory.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-memory-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

# Disk Checks
- name: Check check-disk-usage
  command: sensuctl check create check-disk-usage \
          --command check-disk-usage.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-disk-checks,sensu-ruby-runtime \
          --handlers slack
  run_once: true
  ignore_errors: true

- name: Check check-fstab-mounts
  command: sensuctl check create check-fstab-mounts \
          --command check-fstab-mounts.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-disk-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-disk
  command: sensuctl check create metrics-disk \
          --command metrics-disk.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-disk-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-disk-capacity
  command: sensuctl check create metrics-disk-capacity \
          --command metrics-disk-capacity.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-disk-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true

- name: Check metrics-disk-usage
  command: sensuctl check create metrics-disk-usage \
          --command metrics-disk-usage.rb \
          --interval 60 \
          --subscriptions linux \
          --runtime-assets sensu-plugins-disk-checks,sensu-ruby-runtime
  run_once: true
  ignore_errors: true
