---
image: "docker:latest"
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"

cache:
  paths:
    - .pip/
    - virtenv/

before_script:
  - apk add python3 python3-dev libffi-dev build-base py-setuptools ansible

molecule:
  stage: test

  script:
    - docker -v
    - python -V
    - pip3 install cffi ansible molecule docker
    - ansible --version
    - molecule --version
    - molecule test
