---
- name: Copy assets files to host server
  copy:
    src: files/assets
    dest: /opt/sensu
    owner: sensu
    group: sensu
    mode: '0644'

# Install ASSET Ruby Runtime for RedHat
- name: Install ASSET Ruby Runtime CentOS
  command: sensuctl create \
          --file /opt/sensu/assets/sensu-ruby-runtime-0.0.9-centos-amd64.yml
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

# Install ASSET Ruby Runtime for Debian
- name: Install ASSET Ruby Runtime Debian
  command: sensuctl create \
          --file /opt/sensu/assets/sensu-ruby-runtime-0.0.9-debian-amd64.yml
  run_once: true
  when: ansible_os_family == 'Debian'
  ignore_errors: true


# Install ASSET for checks
- import_tasks: assets/assets-linux.yml
  tags: assets-linux
