---
- name: Install Plugins Packages Ubuntu/Debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "gcc"
      - "python-pip"
      - "ruby"
      - "python-setuptools"
      - "numactl"
  when: ansible_os_family == 'Debian'

- name: Install Plugins Packages RHEL/CentOS
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "gcc"
      - "python-pip"
      - "ruby"
      - "python-setuptools"
      - "numactl"
  when: ansible_os_family == 'RedHat'
