---
- name: Download Script to Add repository Ubuntu/Debian
  get_url:
    url: https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh
    dest: /tmp/script-sensu-backend.deb.sh
    mode: '0766'
  when: ansible_os_family == 'Debian'

- name: Run script to install Sensu Backend
  command: /tmp/script-sensu-backend.deb.sh
  when: ansible_os_family == 'Debian'

- name: Download Script to Add repository RHEL/CentOS
  get_url:
    url: https://packagecloud.io/install/repositories/sensu/stable/script.rpm.sh
    dest: /tmp/script-sensu-backend.rpm.sh
    mode: '0766'
  when: ansible_os_family == 'RedHat'

- name: Run script to install Sensu Backend
  command: /tmp/script-sensu-backend.rpm.sh
  when: ansible_os_family == 'RedHat'

- name: Install Packages Ubuntu/Debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "sensu-go-backend"
      - "sensu-go-cli"
  when: ansible_os_family == 'Debian'

- name: Install Packages RHEL/CentOS
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "sensu-go-backend"
      - "sensu-go-cli"
  when: ansible_os_family == 'RedHat'

- name: Create config file sensu-backend
  template:
    src: backend.yml.j2
    dest: /etc/sensu/backend.yml
    owner: "{{ user_sensu }}"
    group: "{{ group_sensu }}"
  notify: Restart sensu-backend service

- name: Ensure the sensu-backend is enabled
  systemd:
    name: sensu-backend
    enabled: true
    state: restarted
    daemon_reload: true

- name: Validate if port is listening
  wait_for:
    host: "127.0.0.1"
    port: 8080
    delay: 10
    state: started

- name: Sensuctl configure
  command: "sensuctl configure --non-interactive --username {{ default_user }} \
            --password {{ default_pass }} --url http://localhost:8080 \
            --format tabular --namespace default"
