---
- name: Download Script to Add repository Ubuntu/Debian
  get_url:
    url: https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh
    dest: /tmp/script-sensu-agent.deb.sh
    mode: '0766'
  when: ansible_os_family == 'Debian'

- name: Run script to install Sensu Agent
  script: /tmp/script-sensu-agent.deb.sh
  when: ansible_os_family == 'Debian'

- name: Download Script to Add repository RHEL/CentOS
  get_url:
    url: https://packagecloud.io/install/repositories/sensu/stable/script.rpm.sh
    dest: /tmp/script-sensu-agent.rpm.sh
    mode: '0766'
  when: ansible_os_family == 'RedHat'

- name: Run script to install Sensu Agent
  script: /tmp/script-sensu-agent.rpm.sh
  when: ansible_os_family == 'RedHat'

- name: Install Packages Ubuntu/Debian
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - "sensu-go-agent"
  when: ansible_os_family == 'Debian'

- name: Install Packages RHEL/CentOS
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "sensu-go-agent"
  when: ansible_os_family == 'RedHat'

- name: Define Subscritions
  set_fact:
    all_subs: "{{ subs_default + sensu_client_subs }}"

- name: Create config file sensu-agent
  template:
    src: agent.yml.j2
    dest: /etc/sensu/agent.yml
    owner: "{{ user_sensu }}"
    group: "{{ group_sensu }}"
  with_items: "{{ all_subs }}"
  notify: Restart sensu-agent service

- name: Ensure the sensu-agent is enabled
  systemd:
    name: sensu-agent
    enabled: true
    state: restarted
    daemon_reload: true
