---
# Slack handler
- name: Install ASSET sensu-slack-handler
  command: sensuctl create --file /opt/sensu/assets/sensu-slack-handler.yml
  run_once: true
  when: slack
  ignore_errors: true

# CPU Checks
- name: Install ASSET sensu-plugins-cpu-checks CentOS
  command: sensuctl create \
    --file /opt/sensu/assets/sensu-plugins-cpu-checks-4.0.0-centos-amd64.yml
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

- name: Install ASSET sensu-plugins-cpu-checks Debian
  command: sensuctl create \
    --file /opt/sensu/assets/sensu-plugins-cpu-checks-4.0.0-debian-amd64.yml
  run_once: true
  when: ansible_os_family == 'Debian'
  ignore_errors: true

# Memory
- name: Install ASSET sensu-plugins-memory-checks CentOS
  command: sensuctl create \
    --file /opt/sensu/assets/sensu-plugins-memory-checks-4.0.0-centos-amd64.yml
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

- name: Install ASSET sensu-plugins-memory-checks Debian
  command: sensuctl create \
    --file /opt/sensu/assets/sensu-plugins-memory-checks-4.0.0-debian-amd64.yml
  run_once: true
  when: ansible_os_family == 'Debian'
  ignore_errors: true

# Disk
- name: Install ASSET sensu-plugins-disk-checks CentOS
  command: sensuctl create \
    --file /opt/sensu/assets/sensu-plugins-disk-checks-5.0.0-centos-amd64.yml
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

- name: Install ASSET sensu-plugins-disk-checks Debian
  command: sensuctl create \
    --file /opt/sensu/assets/sensu-plugins-disk-checks-5.0.0-debian-amd64.yml
  run_once: true
  when: ansible_os_family == 'Debian'
  ignore_errors: true
