---
# CPU Checks
- name: Install ASSET sensu-plugins-cpu-checks CentOS
  command: sensuctl asset create sensu-plugins-cpu-checks \
         --url "https://assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_centos_linux_amd64.tar.gz" \
         --sha512 "518e7c17cf670393045bff4af318e1d35955bfde166e9ceec2b469109252f79043ed133241c4dc96501b6636a1ec5e008ea9ce055d1609865635d4f004d7187b"
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

- name: Install ASSET sensu-plugins-cpu-checks Debian
  command: sensuctl asset create sensu-plugins-cpu-checks \
         --url "https://assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_debian_linux_amd64.tar.gz" \
         --sha512 "da5a183ad1a1f76962561eed659c6184b3e5d6a412432e1ccb4297cce123c41f9a8bb4fdb9ab19663aada978ea862ab2bd5f00bc91e4769ddd87543f5662b3af"
  run_once: true
  when: ansible_os_family == 'Debian'
  ignore_errors: true

# Memory
- name: Install ASSET sensu-plugins-memory-checks CentOS
  command: sensuctl asset create sensu-plugins-memory-checks \
         --url "https://assets.bonsai.sensu.io/c5391d4ae186484226732344b35cf95c0b07b8ec/sensu-plugins-memory-checks_4.0.0_centos_linux_amd64.tar.gz"\
         --sha512 "ea297a85aa3612da7f78d948f9784443fffac511040c5130a2dcde7191a0004044c2ef881e665520cbc64431955ab19920d84de6b5fed85c63da7091c4b93bf0"
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

- name: Install ASSET sensu-plugins-memory-checks Debian
  command: sensuctl asset create sensu-plugins-memory-checks \
         --url "https://assets.bonsai.sensu.io/c5391d4ae186484226732344b35cf95c0b07b8ec/sensu-plugins-memory-checks_4.0.0_debian_linux_amd64.tar.gz" \
         --sha512 "3c61ab6f4eb5dea4ee816e4f9a4f857660ac32648d0ecd7804e1827351d8fe021f29e557d9600ecac8cd16d261c8ff2dc113790a544ce1148a8cb321546552d6"
  run_once: true
  when: ansible_os_family == 'Debian'
  ignore_errors: true

# Vmstat
- name: Install ASSET sensu-plugins-vmstats CentOS
  command: sensuctl asset create sensu-plugins-vmstats \
         --url "https://assets.bonsai.sensu.io/5c97f93791b98b2542c5c9739e88ca28b76a95ac/sensu-plugins-vmstats_2.0.0_centos_linux_amd64.tar.gz"\
         --sha512 "366eb41a1ad3b7750d7de5f510b6a17393729eac09d4b786e9af440b8036a737fa3ff8da1e137238edce8585898fa936cf096c4c12c226f628d998ca59769e6f"
  run_once: true
  when: ansible_os_family == 'RedHat'
  ignore_errors: true

